# Form implementation generated from reading ui file 'd:\ollama\llama3_python\ollama.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2094, 1220)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1080, 40, 951, 31))
        self.label.setStyleSheet("QLabel{\n"
"background-color :qlineargradient(spread:pad, x1:0.631579, y1:0.222, x2:1, y2:1, stop:0 rgba(165, 81, 81, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font-size: 30px;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 831, 41))
        self.label_2.setStyleSheet("QLabel{\n"
"background-color : green;\n"
"font-size: 30px;\n"
"\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 70, 831, 1031))
        self.plainTextEdit.setStyleSheet("QPlainTextEdit{\n"
"font-size:30px;\n"
"}")
        self.plainTextEdit.setPlaceholderText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1810, 1120, 211, 31))
        self.label_3.setStyleSheet("QLabel {\n"
"background-color :rgb(174, 176, 155)\n"
"}")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(840, 200, 241, 301))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color : green;\n"
"font-size: 30px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(1080, 70, 951, 1041))
        self.textBrowser.setStyleSheet("QTextBrowser{\n"
"font-size: 30px;\n"
"}")
        self.textBrowser.setMarkdown("")
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(840, 500, 241, 291))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-color :qlineargradient(spread:pad, x1:0.631579, y1:0.222, x2:1, y2:1, stop:0 rgba(165, 81, 81, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font-size: 27px;\n"
"\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2094, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Your answer: "))
        self.label_2.setText(_translate("MainWindow", "write your question hier :"))
        self.label_3.setText(_translate("MainWindow", "Developered by Ahmad Al Madani"))
        self.pushButton.setText(_translate("MainWindow", "Generate"))
        self.pushButton_2.setText(_translate("MainWindow", "Clear output"))
